### ISSUE TITLE
Running with -c command results in crash

### ISSUE THREAD

**Issue by Maaster** [circleguard/wtc-lzma-compressor#1]
Command used for testing:
"python  .\anticheat.py -m 1844417 -c"

Error: "struct.error: byte format requires -128 <= number <= 127"

Full stacktrace:
![image](https://user-images.githubusercontent.com/6342894/52136709-ffa4c500-2648-11e9-9c4a-00f5a5b6cc19.png)

**Comment by Liam-DeVoe** [comment]
closed with 472e7d5c7c8c833bceab7b360a4280bda6d2db5f
